# FSLogix: Redirections Generator
# Generates FSLogix redirections.xml from best-practice templates covering browser caches, Teams (classic + new), new Outlook, OneDrive, Slack, Spotify, and more. Based on Aaron Parker's curated list (MIT).
#Category: FSLogix: Configuration
#Run On: on_demand
#Timeout: 15
#Execution Mode: serial

#Requires -Version 5.1
<#
.SYNOPSIS
    Redirections.xml Generator — create FSLogix redirections from best-practice templates.
.DESCRIPTION
    Generates a redirections.xml from curated exclusion lists covering browser caches,
    Teams, new Outlook, OneDrive, and more. Based on Aaron Parker's Redirections.csv (MIT).
.NOTES
    FleetCTRL Script Library | Category: Redirections & App Masking
    Trigger: On-Demand | Admin Required: No | Destructive: No (creates file)
#>
[CmdletBinding()]
param(
    [string]$OutputPath = '',
    [switch]$IncludeWarnings
)

$ErrorActionPreference = 'SilentlyContinue'

# Best-practice exclusions (from Aaron Parker's Redirections.csv, MIT license)
$exclusions = @(
    # Windows system
    @{ Path = 'AppData\Local\CrashDumps'; Copy = 0; Desc = 'Windows crash dumps' }
    @{ Path = 'AppData\Local\Microsoft\Terminal Server Client\Cache'; Copy = 0; Desc = 'RDP client cache' }
    
    # Browser caches
    @{ Path = 'AppData\Local\Google\Chrome\User Data\Default\Cache'; Copy = 0; Desc = 'Chrome browser cache' }
    @{ Path = 'AppData\Local\Google\Chrome\User Data\Default\Code Cache'; Copy = 0; Desc = 'Chrome WebAssembly cache'; Warning = 'May impact WebAssembly app performance' }
    @{ Path = 'AppData\Local\Microsoft\Edge\User Data\Default\Cache'; Copy = 0; Desc = 'Edge browser cache' }
    @{ Path = 'AppData\Local\Microsoft\Edge\User Data\Default\Code Cache'; Copy = 0; Desc = 'Edge WebAssembly cache'; Warning = 'May impact WebAssembly app performance' }
    
    # Teams Classic
    @{ Path = 'AppData\Roaming\Microsoft\Teams\media-stack'; Copy = 0; Desc = 'Teams Classic media stack tracing' }
    @{ Path = 'AppData\Roaming\Microsoft\Teams\Service Worker'; Copy = 0; Desc = 'Teams Classic service worker' }
    @{ Path = 'AppData\Roaming\Microsoft\Teams\meeting-addin\Cache'; Copy = 0; Desc = 'Teams Classic meeting add-in cache' }
    
    # New Teams
    @{ Path = 'AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\Logs'; Copy = 0; Desc = 'New Teams logs' }
    @{ Path = 'AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\PerfLogs'; Copy = 0; Desc = 'New Teams performance logs' }
    @{ Path = 'AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\WV2Profile_tfw\WebStorage'; Copy = 0; Desc = 'New Teams WebView2 storage' }
    @{ Path = 'AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\WV2Profile_tfw\GPUCache'; Copy = 0; Desc = 'New Teams GPU cache' }
    @{ Path = 'AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\WV2Profile_tfw\Service Worker\CacheStorage'; Copy = 0; Desc = 'New Teams service worker cache'; Warning = 'Slower app launches due to script redownload' }
    @{ Path = 'AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\WV2Profile_tfw\Code Cache'; Copy = 0; Desc = 'New Teams code cache'; Warning = 'Slower app launches due to script redownload' }
    
    # Windows Server 2022 Teams fix
    @{ Path = 'AppData\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\TempState'; Copy = 0; Desc = 'Start Menu temp state (Server 2022 Teams fix)'; Warning = 'Needed for Windows Server 2022' }
    @{ Path = 'AppData\Local\Packages\Microsoft.Windows.ShellExperienceHost_cw5n1h2txyewy\TempState'; Copy = 0; Desc = 'Shell Experience temp state (Server 2022 Teams fix)'; Warning = 'Needed for Windows Server 2022' }
    
    # New Outlook
    @{ Path = 'AppData\Local\Microsoft\olk\logs'; Copy = 0; Desc = 'New Outlook diagnostic logs' }
    @{ Path = 'AppData\Local\Microsoft\olk\EbWebView\default\WebStorage'; Copy = 0; Desc = 'New Outlook WebStorage' }
    @{ Path = 'AppData\Local\Microsoft\olk\EbWebView\default\Service Worker\CacheStorage'; Copy = 0; Desc = 'New Outlook service worker cache'; Warning = 'Slower app launches' }
    @{ Path = 'AppData\Local\Microsoft\olk\EbWebView\default\Code Cache'; Copy = 0; Desc = 'New Outlook code cache'; Warning = 'Slower app launches' }
    @{ Path = 'AppData\Local\Microsoft\olk\EbWebView\default\Cache'; Copy = 0; Desc = 'New Outlook network cache'; Warning = 'Resources need re-download' }
    @{ Path = 'AppData\Local\Microsoft\olk\Attachments'; Copy = 0; Desc = 'New Outlook attachments cache'; Warning = 'Increased app launch time' }
)

# Filter warnings if not included
if (-not $IncludeWarnings) {
    $exclusions = $exclusions | Where-Object { -not $_.Warning }
}

# Build XML
$xmlContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by FleetCTRL FSLogix Redirections Generator on $([datetime]::UtcNow.ToString('yyyy-MM-dd HH:mm:ss')) UTC -->
<!-- Based on Aaron Parker's curated exclusion list (MIT License) -->
<FrxProfileFolderRedirection ExcludeCommonFolders="0">
  <Excludes>
"@

foreach ($excl in $exclusions) {
    $xmlContent += "`n    <!-- $($excl.Desc) -->"
    if ($excl.Warning) {
        $xmlContent += "`n    <!-- WARNING: $($excl.Warning) -->"
    }
    $xmlContent += "`n    <Exclude Copy=`"$($excl.Copy)`">$($excl.Path)</Exclude>"
}

$xmlContent += @"

  </Excludes>
  <Includes>
  </Includes>
</FrxProfileFolderRedirection>
"@

# Determine output path
if (-not $OutputPath) {
    $redirFolder = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\FSLogix\Profiles' -Name 'RedirXMLSourceFolder' -ErrorAction SilentlyContinue).RedirXMLSourceFolder
    if ($redirFolder -and (Test-Path $redirFolder)) {
        $OutputPath = Join-Path -Path $redirFolder -ChildPath 'Redirections.xml'
    }
}

$output = @{
    Timestamp       = [datetime]::UtcNow.ToString('o')
    ComputerName    = $env:COMPUTERNAME
    ExclusionCount  = $exclusions.Count
    IncludeWarnings = [bool]$IncludeWarnings
    XmlContent      = $xmlContent
}

if ($OutputPath) {
    try {
        $xmlContent | Out-File -FilePath $OutputPath -Encoding UTF8 -Force -ErrorAction Stop
        $output['OutputPath'] = $OutputPath
        $output['Status'] = 'Written'
    } catch {
        $output['OutputPath'] = $OutputPath
        $output['Status'] = 'Failed'
        $output['Error'] = $_.Exception.Message
    }
} else {
    $output['Status'] = 'Generated'
    $output['Message'] = 'No output path specified and no RedirXMLSourceFolder configured — XML content returned in response only'
}

$output | ConvertTo-Json -Depth 3
